#!/bin/bash


if [ $# == 1 ]; then 
  name=$1
else
  name=$(basename $PWD)
fi

script="curl -u 'mobangjack' https://api.github.com/user/repos -d '{\"name\":\"$name\"}' &&
    git init && 
    git remote add origin $REPO/$name && 

echo "executing script: $script"

bash -exec "$script"

